server {
    listen 80;
    server_name localhost;

    # THÊM DÒNG NÀY ĐỂ GIỮ NGUYÊN CỔNG 4000
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Thứ tự tìm kiếm:
        # 1. Tìm file chính xác ($uri)
        # 2. Tìm file gắn thêm đuôi .html ($uri.html) -> BÍ QUYẾT ĐỂ GÕ /login RA login.html
        # 3. Tìm thư mục ($uri/)
        # 4. Nếu không thấy gì, đá về trang chủ index.html
        try_files $uri $uri.html $uri/ /index.html;
    }

    # 2. Đường dành riêng cho Admin
    location /admin {
        try_files $uri $uri.html $uri/ /admin.html;
    }
}