server {
    listen 80;
    server_name localhost;

    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    # 2. Đường dành riêng cho Admin
    location /dashboard {
        try_files $uri $uri.html $uri/ /admin.html;
    }

    location /download-root {
        alias /certs/ca.crt; 
        add_header Content-Disposition 'attachment; filename="UIT_Root_CA.crt"';
        default_type application/octet-stream;
    }

    location /download-int {
        alias /certs/int-ca.crt; 
        add_header Content-Disposition 'attachment; filename="UIT_Intermediate_CA.crt"';
        default_type application/octet-stream;
    }
}