server {
    listen 80;
    server_name localhost;

    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Thứ tự tìm kiếm:
        # 1. Tìm file chính xác ($uri)
        # 2. Tìm file gắn thêm đuôi .html ($uri.html) -> BÍ QUYẾT ĐỂ GÕ /login RA login.html
        # 3. Tìm thư mục ($uri/)
        # 4. Nếu không thấy gì, đá về trang chủ index.html
        try_files $uri $uri.html $uri/ /index.html;
    }

    # 2. Đường dành riêng cho Admin
    location /admin {
        try_files $uri $uri.html $uri/ /admin.html;
    }

    location /download-root {
        alias /certs/ca.crt; 
        add_header Content-Disposition 'attachment; filename="UIT_Root_CA.crt"';
        default_type application/octet-stream;
    }

    location /download-int {
        alias /certs/int-ca.crt; 
        add_header Content-Disposition 'attachment; filename="UIT_Intermediate_CA.crt"';
        default_type application/octet-stream;
    }
}