# Dùng bản Nginx siêu nhẹ
FROM nginx:alpine

# Copy file index.html của bạn đè lên trang mặc định của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Mở cửa cổng 80 bên trong container
EXPOSE 80