services:
  # 1. API GATEWAY
  kong:
    image: kong:3.4-ubuntu
    container_name: kong-api
    volumes:
      - ../gateway/kong.yml:/usr/local/kong/declarative/kong.yml
      - ../certs:/certs
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"
      - "127.0.0.1:8001:8001"
    networks:
      - capstone-net

  #2. FRONTEND WEB
  frontend-web:
    build: 
      context: ../frontend
      dockerfile: Dockerfile
    container_name: frontend-web
    ports:
      - "4000:80"
    networks:
      - capstone-net
    depends_on:
      - kong


  # 3. BACKEND SERVICE
  order-service:
    build: ../services/order-service
    container_name: backend-order-api
    #ports:
    #  - "3000:3000"
    expose:
      - "3000"
    environment:
      PORT: 3000
      VAULT_ADDR: "http://vault-server:8200"
      #VAULT_TOKEN: "my-root-token"
      #WEBHOOK_SECRET: "day-la-key-sieu-bao-mat-moi" # Dùng cho HMAC
    depends_on:
      - vault
    volumes:
      - ../certs:/app/certs
      - vault-token-share:/app/vault-token-share
    networks:
      - capstone-net

  product-service:
    build: ../services/product-service
    container_name: backend-product-api
    expose:
      - "3001"
    environment:
      PORT: 3001
      VAULT_ADDR: "http://vault-server:8200"
      #DATABASE_URL: ${DATABASE_URL} # Nếu dùng Vault thì có thể bỏ dòng này trong Compose
    volumes:
      - ../certs:/app/certs
      - vault-token-share:/app/vault-token-share # Quan trọng: Để lấy token từ Vault Agent
    networks:
      - capstone-net
    depends_on:
      - vault

  # ==========================================
  # 7. MOCK PAYMENT GATEWAY (GIẢ LẬP VNPAY)
  # ==========================================
  mock-vnpay:
    build: ../services/mock-vnpay # Thư mục chứa code mock-vnpay.js và Dockerfile
    container_name: mock-vnpay
    ports:
      - "4001:4001" # Mở cổng 4001 ra ngoài để trình duyệt có thể redirect tới
    environment:
      PORT: 4001
      # Nếu code mock-vnpay của bạn có dùng biến môi trường để đọc Secret Webhook thì thêm vào đây:
      WEBHOOK_SECRET: "day-la-key-sieu-bao-mat-moi"
    networks:
      - capstone-net

  # 4. IDENTITY PROVIDER (KEYCLOAK)
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak-idp
    command: start-dev --import-realm 
    environment:
      KC_PROXY: edge
      # THAY ĐỔI 2: Ép các đường link Keycloak tạo ra phải dùng cổng 8000 của Kong
      KC_HOSTNAME_URL: http://localhost:8000
      KC_HOSTNAME_ADMIN_URL: http://localhost:8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
    #  - "8080:8080"
       - "127.0.0.1:8080:8080" # Chỉ expose cổng 8080 ra localhost để tránh xung đột với Kong
    volumes:
      - ./realm-full.json:/opt/keycloak/data/import/realm.json
    networks:
      - capstone-net

  # 4. SECRET MANAGEMENT (VAULT)
  consul:
    image: hashicorp/consul:1.15
    container_name: consul-storage
    command: agent -server -bootstrap-expect=1 -ui -client=0.0.0.0
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    volumes:
      - consul-data:/consul/data
    ports:
      - "127.0.0.1:8500:8500"
    networks:
      - capstone-net

  # 5. VAULT - Két sắt (Chạy chế độ Server Mode)
  vault:
    image: hashicorp/vault:1.13
    container_name: vault-server
    user: root
    #ports:
    #  - "8200:8200"
    expose:
      - "8200"
    volumes:
      - ./vault-config.hcl:/vault/config/vault-config.hcl:ro
    # Chạy lệnh server với file cấu hình thay vì dev mode
    command: vault server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    depends_on:
      - consul
    networks:
      - capstone-net

  # 6. VAULT AGENT - Ông thư ký (Giữ nguyên, chỉ cần khớp networks)
  vault-agent:
    image: hashicorp/vault:1.13
    container_name: vault-agent
    user: root
    volumes:
      - ./vault-agent.hcl:/etc/vault/agent.hcl
      - vault-token-share:/app/vault-token-share
      - ./.vault-ids:/etc/vault
    command: sh -c "mkdir -p /app/vault-token-share && vault agent -config=/etc/vault/agent.hcl"
    depends_on:
      - vault
    networks:
      - capstone-net

    # ==========================================
  # ELK STACK (LOGGING & MONITORING)
  # ==========================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Tắt xác thực để demo cho nhanh
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Giới hạn RAM
    #ports:
    #  - "9200:9200"
    expose:
      - "9200"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    networks:
      - capstone-net  

  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.1
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    #ports:
    #  - "5044:5044"
    expose:
      - "5044"
    depends_on:
      - elasticsearch
    networks:
      - capstone-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana
    ports:
      - "127.0.0.1:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - capstone-net

networks:
  capstone-net:
    driver: bridge

volumes:
  consul-data:       # Lưu trữ dữ liệu Consul xuống ổ cứng
  vault-token-share: # Chia sẻ Token giữa Agent và Backend
  elastic-data:      # Lưu trữ dữ liệu Elasticsearch xuống ổ cứng