input {
  # Mở cổng HTTP 5044 để nhận log từ Node.js bắn sang
  input {
  http {
    port => 5044
    ssl => true
    ssl_certificate => "/certs/kong-bundle.crt" # Tái sử dụng cert của Kong trong nội bộ cho tiện
    ssl_key => "/certs/kong.key"
  }
}
}

filter {
  # (Có thể thêm filter ở đây nếu muốn lọc dữ liệu, hiện tại để trống)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}" # Tên index lưu trong Elasticsearch
  }
  # In ra màn hình console của Logstash để dễ debug
  stdout { codec => rubydebug }
}