input {
  # Mở cổng HTTP 5044 để nhận log từ Node.js bắn sang
  http {
    port => 5044
    codec => json
  }
}

filter {
  # (Có thể thêm filter ở đây nếu muốn lọc dữ liệu, hiện tại để trống)
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "security-logs-%{+YYYY.MM.dd}" # Tên index lưu trong Elasticsearch
  }
  # In ra màn hình console của Logstash để dễ debug
  stdout { codec => rubydebug }
}