-- ============================================================
--  Cloud-API-Based-Network-Application-Security
--  Database: Laptop Store — Đã gỡ mã hóa, Cập nhật UUID mới (Lần cuối)
-- ============================================================

DROP TYPE IF EXISTS order_status CASCADE;
CREATE TYPE order_status AS ENUM ('Pending','Processing','Shipped','Delivered','Cancelled');

DROP TABLE IF EXISTS sessions   CASCADE;
DROP TABLE IF EXISTS orders     CASCADE;
DROP TABLE IF EXISTS products   CASCADE;
DROP TABLE IF EXISTS users      CASCADE;
DROP TABLE IF EXISTS brands     CASCADE;
DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE brands (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    country     VARCHAR(50),
    website     VARCHAR(100),
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id          UUID         PRIMARY KEY,
    email       VARCHAR(100) NOT NULL UNIQUE,
    full_name   VARCHAR(100) NOT NULL,
    phone       TEXT,
    city        VARCHAR(100),
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE products (
    sku         VARCHAR(20)    PRIMARY KEY,
    name        VARCHAR(150)   NOT NULL,
    brand_id    INTEGER        NOT NULL REFERENCES brands(id),
    category_id INTEGER        NOT NULL REFERENCES categories(id),
    price       NUMERIC(10,2)  NOT NULL,
    specs       TEXT,
    stock       INTEGER        DEFAULT 50,
    created_at  TIMESTAMP      DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders (
    id              INTEGER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         UUID           NOT NULL REFERENCES users(id),
    sku             VARCHAR(20)    NOT NULL REFERENCES products(sku),
    item_name       VARCHAR(150)   NOT NULL,
    qty             INTEGER        NOT NULL DEFAULT 1 CHECK (qty > 0),
    unit_price      NUMERIC(10,2)  NOT NULL,
    total_price     NUMERIC(10,2)  GENERATED ALWAYS AS (qty * unit_price) STORED,
    status          order_status   DEFAULT 'Pending',
    payment_status VARCHAR(20)     DEFAULT 'Unpaid',
    order_date      DATE           NOT NULL,
    created_at      TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
    customer_phone  TEXT
);

CREATE INDEX idx_orders_user_id  ON orders(user_id);
CREATE INDEX idx_orders_sku      ON orders(sku);
CREATE INDEX idx_users_email     ON users(email);

-- ============================================================
--  NẠP DỮ LIỆU
-- ============================================================
INSERT INTO brands (name, country, website) VALUES
('Dell', 'USA', 'https://www.dell.com'), ('Apple', 'USA', 'https://www.apple.com'),
('Lenovo', 'China', 'https://www.lenovo.com'), ('HP', 'USA', 'https://www.hp.com'),
('ASUS', 'Taiwan', 'https://www.asus.com'), ('MSI', 'Taiwan', 'https://www.msi.com');

INSERT INTO categories (name, description) VALUES
('Budget', 'Affordable laptops'), ('Business', 'Office work'), ('Enterprise', 'High-security'), 
('Premium', 'Thin & light'), ('Gaming', 'High-performance'), ('Convertible', '2-in-1'), ('Pro', 'Apple pro');

-- Nạp 20 Khách hàng (Sử dụng các UUID mới nhất bạn vừa cung cấp)
INSERT INTO users (id, email, full_name, phone, city) VALUES
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'an.nguyen@email.com',   'Nguyễn Văn An',   '0901234567', 'Hà Nội'),
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'bich.tran@email.com',   'Trần Thị Bích',   '0912345678', 'Thành phố Hồ Chí Minh'),
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'cuong.le@email.com',    'Lê Minh Cường',   '0923456789', 'Đà Nẵng'),
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'dung.pham@email.com',   'Phạm Thị Dung',   '0934567890', 'Cần Thơ'),
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'em.hoang@email.com',    'Hoàng Văn Em',    '0945678901', 'Hải Phòng'),
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'phuong.vu@email.com',   'Vũ Thị Phương',   '0956789012', 'Huế'),
('90746ada-3243-44b3-9e3b-ebe796e15060', 'giang.do@email.com',    'Đỗ Văn Giang',    '0967890123', 'Khánh Hòa'),
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'hoa.bui@email.com',     'Bùi Thị Hoa',     '0978901234', 'Đồng Nai'),
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'inh.ngo@email.com',     'Ngô Văn Inh',     '0989012345', 'Gia Lai'),
('3c10969e-dda0-4cef-a929-8dacf941d049', 'jen.dinh@email.com',    'Đinh Thị Jên',    '0990123456', 'Đắk Lắk'),
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'khoa.ly@email.com',     'Lý Văn Khoa',     '0901357902', 'Lâm Đồng'),
('0afe9363-4743-4629-8fc7-576135007940', 'lan.mai@email.com',     'Mai Thị Lan',     '0912468013', 'Quảng Ninh'),
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'minh.truong@email.com', 'Trương Văn Minh', '0923579124', 'Nghệ An'),
('201d806f-9f01-4e60-8574-9bd544c9994d', 'ngoc.cao@email.com',    'Cao Thị Ngọc',    '0934680235', 'Thanh Hóa'),
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'oanh.duong@email.com',  'Dương Văn Oanh',  '0945791346', 'Lào Cai'),
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'phuc.phan@email.com',   'Phan Thị Phúc',   '0956802457', 'Bắc Ninh'),
('29949fac-e389-4f79-bb15-e8682827cd2b', 'quan.ta@email.com',     'Tạ Văn Quân',     '0967913568', 'An Giang'),
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'ruong.luu@email.com',   'Lưu Thị Rương',   '0978024679', 'Cà Mau'),
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'son.ha@email.com',      'Hà Văn Sơn',      '0989135780', 'Vĩnh Long'),
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'tuyet.kieu@email.com',  'Kiều Thị Tuyết',  '0990246891', 'Tây Ninh');

-- Nạp 15 Sản phẩm đại diện
INSERT INTO products (sku, name, brand_id, category_id, price) VALUES
('DELL-001', 'Dell Inspiron 15 3511', 1, 1, 699.00),
('DELL-007', 'Dell XPS 13 9315', 1, 4, 1499.00),
('APPL-001', 'MacBook Air M1 13"', 2, 4, 999.00),
('APPL-006', 'MacBook Pro M3 14"', 2, 7, 1999.00),
('LNVO-002', 'Lenovo IdeaPad Slim 5', 3, 1, 699.00),
('LNVO-007', 'Lenovo Legion 5 Gen 8', 3, 5, 1099.00),
('HP-004', 'HP ProBook 440 G10', 4, 2, 950.00),
('HP-008', 'HP Omen 16 Gaming', 4, 5, 1299.00),
('ASUS-003', 'ASUS ZenBook 14 OLED', 5, 4, 999.00),
('ASUS-008', 'ASUS ROG Zephyrus G14', 5, 5, 1499.00),
('MSI-001', 'MSI Modern 14 C12M', 6, 2, 699.00),
('MSI-005', 'MSI Katana 15 B12V', 6, 5, 999.00),
('APPL-008', 'MacBook Pro M3 Max 16"', 2, 7, 3499.00),
('DELL-012', 'Dell Alienware m15 R7', 1, 5, 2499.00),
('ASUS-011', 'ASUS ProArt Studiobook 16', 5, 7, 2199.00);

-- Nạp 100 Đơn hàng (Khớp tuyệt đối với UUID mới của 20 user)
INSERT INTO orders (user_id, sku, item_name, qty, unit_price, status, order_date) VALUES
-- User 1
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Delivered', '2024-01-10'),
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'APPL-001', 'MacBook Air M1 13"', 1, 999.00, 'Shipped', '2024-02-15'),
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Pending', '2024-03-20'),
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'HP-004', 'HP ProBook 440 G10', 2, 950.00, 'Delivered', '2024-04-05'),
('22cdfadf-6986-40b0-ab59-af5a27a73b6f', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Cancelled', '2024-05-12'),
-- User 2
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Delivered', '2024-01-12'),
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Processing', '2024-02-18'),
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Shipped', '2024-03-25'),
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Delivered', '2024-04-08'),
('4b3a8ac2-79c5-402d-b33a-5f93305c294a', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Pending', '2024-05-15'),
-- User 3
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Delivered', '2024-01-14'),
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 1, 1099.00, 'Shipped', '2024-02-20'),
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Processing', '2024-03-28'),
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'APPL-008', 'MacBook Pro M3 Max 16"', 1, 3499.00, 'Delivered', '2024-04-10'),
('9e93d3d9-609f-45a4-9bdc-e46a39e74006', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Cancelled', '2024-05-18'),
-- User 4
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'DELL-001', 'Dell Inspiron 15 3511', 2, 699.00, 'Delivered', '2024-01-16'),
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'APPL-001', 'MacBook Air M1 13"', 1, 999.00, 'Shipped', '2024-02-22'),
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Delivered', '2024-03-30'),
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Pending', '2024-04-12'),
('c4fad839-57f1-4096-8422-4f3b6946ab54', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Delivered', '2024-05-20'),
-- User 5
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Delivered', '2024-01-18'),
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 2, 699.00, 'Shipped', '2024-02-25'),
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Processing', '2024-04-02'),
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Delivered', '2024-04-15'),
('0e36e7ec-f694-436e-b1b7-f1896f7d6fb9', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Cancelled', '2024-05-22'),
-- User 6
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Delivered', '2024-01-20'),
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 1, 1099.00, 'Pending', '2024-02-28'),
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Delivered', '2024-04-04'),
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'APPL-008', 'MacBook Pro M3 Max 16"', 1, 3499.00, 'Shipped', '2024-04-18'),
('78bce29e-2a5a-456c-b02a-7a4e6a1522cf', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Delivered', '2024-05-25'),
-- User 7
('90746ada-3243-44b3-9e3b-ebe796e15060', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Delivered', '2024-01-22'),
('90746ada-3243-44b3-9e3b-ebe796e15060', 'APPL-001', 'MacBook Air M1 13"', 2, 999.00, 'Shipped', '2024-03-01'),
('90746ada-3243-44b3-9e3b-ebe796e15060', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Processing', '2024-04-06'),
('90746ada-3243-44b3-9e3b-ebe796e15060', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Delivered', '2024-04-20'),
('90746ada-3243-44b3-9e3b-ebe796e15060', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Pending', '2024-05-28'),
-- User 8
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Delivered', '2024-01-24'),
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Delivered', '2024-03-05'),
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Shipped', '2024-04-08'),
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Processing', '2024-04-22'),
('7ca4b19b-1aff-45dc-a33d-0882b7302351', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Delivered', '2024-05-30'),
-- User 9
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Shipped', '2024-01-26'),
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 2, 1099.00, 'Delivered', '2024-03-08'),
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Pending', '2024-04-10'),
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'APPL-008', 'MacBook Pro M3 Max 16"', 1, 3499.00, 'Delivered', '2024-04-25'),
('ea7fea4f-51fe-4a39-b498-a32b4bc546c5', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Cancelled', '2024-06-02'),
-- User 10
('3c10969e-dda0-4cef-a929-8dacf941d049', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Delivered', '2024-01-28'),
('3c10969e-dda0-4cef-a929-8dacf941d049', 'APPL-001', 'MacBook Air M1 13"', 1, 999.00, 'Processing', '2024-03-10'),
('3c10969e-dda0-4cef-a929-8dacf941d049', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Delivered', '2024-04-12'),
('3c10969e-dda0-4cef-a929-8dacf941d049', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Shipped', '2024-04-28'),
('3c10969e-dda0-4cef-a929-8dacf941d049', 'MSI-001', 'MSI Modern 14 C12M', 2, 699.00, 'Delivered', '2024-06-05'),
-- User 11
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Pending', '2024-01-30'),
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Delivered', '2024-03-12'),
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Processing', '2024-04-14'),
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Delivered', '2024-04-30'),
('3966c3c7-9dbd-416b-ba23-4bb0382ea69f', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Shipped', '2024-06-08'),
-- User 12
('0afe9363-4743-4629-8fc7-576135007940', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Delivered', '2024-02-02'),
('0afe9363-4743-4629-8fc7-576135007940', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 1, 1099.00, 'Cancelled', '2024-03-15'),
('0afe9363-4743-4629-8fc7-576135007940', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Delivered', '2024-04-16'),
('0afe9363-4743-4629-8fc7-576135007940', 'APPL-008', 'MacBook Pro M3 Max 16"', 1, 3499.00, 'Pending', '2024-05-02'),
('0afe9363-4743-4629-8fc7-576135007940', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Delivered', '2024-06-10'),
-- User 13
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Shipped', '2024-02-04'),
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'APPL-001', 'MacBook Air M1 13"', 1, 999.00, 'Delivered', '2024-03-18'),
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'ASUS-003', 'ASUS ZenBook 14 OLED', 2, 999.00, 'Processing', '2024-04-18'),
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Delivered', '2024-05-05'),
('a1f85ba9-d0cd-43bc-af1c-2eef2d818d25', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Pending', '2024-06-12'),
-- User 14
('201d806f-9f01-4e60-8574-9bd544c9994d', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Delivered', '2024-02-06'),
('201d806f-9f01-4e60-8574-9bd544c9994d', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Shipped', '2024-03-20'),
('201d806f-9f01-4e60-8574-9bd544c9994d', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Delivered', '2024-04-20'),
('201d806f-9f01-4e60-8574-9bd544c9994d', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Processing', '2024-05-08'),
('201d806f-9f01-4e60-8574-9bd544c9994d', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Delivered', '2024-06-15'),
-- User 15
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Pending', '2024-02-08'),
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 1, 1099.00, 'Delivered', '2024-03-22'),
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Shipped', '2024-04-22'),
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'APPL-008', 'MacBook Pro M3 Max 16"', 2, 3499.00, 'Delivered', '2024-05-10'),
('fa1cac4f-3342-4c27-b776-aadee61e7a0d', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Processing', '2024-06-18'),
-- User 16
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Delivered', '2024-02-10'),
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'APPL-001', 'MacBook Air M1 13"', 1, 999.00, 'Cancelled', '2024-03-24'),
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Delivered', '2024-04-24'),
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Pending', '2024-05-12'),
('66a1d0cc-1dae-49a5-b454-cda35278ea4e', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Delivered', '2024-06-20'),
-- User 17
('29949fac-e389-4f79-bb15-e8682827cd2b', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Shipped', '2024-02-12'),
('29949fac-e389-4f79-bb15-e8682827cd2b', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Delivered', '2024-03-26'),
('29949fac-e389-4f79-bb15-e8682827cd2b', 'DELL-007', 'Dell XPS 13 9315', 2, 1499.00, 'Processing', '2024-04-26'),
('29949fac-e389-4f79-bb15-e8682827cd2b', 'HP-008', 'HP Omen 16 Gaming', 1, 1299.00, 'Delivered', '2024-05-14'),
('29949fac-e389-4f79-bb15-e8682827cd2b', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Pending', '2024-06-22'),
-- User 18
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'MSI-005', 'MSI Katana 15 B12V', 1, 999.00, 'Delivered', '2024-02-14'),
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'LNVO-007', 'Lenovo Legion 5 Gen 8', 1, 1099.00, 'Shipped', '2024-03-28'),
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'DELL-012', 'Dell Alienware m15 R7', 1, 2499.00, 'Delivered', '2024-04-28'),
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'APPL-008', 'MacBook Pro M3 Max 16"', 1, 3499.00, 'Processing', '2024-05-16'),
('c4dcae00-0d9c-476c-a896-ff87d6344fb7', 'ASUS-011', 'ASUS ProArt Studiobook 16', 1, 2199.00, 'Delivered', '2024-06-24'),
-- User 19
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'DELL-001', 'Dell Inspiron 15 3511', 1, 699.00, 'Pending', '2024-02-16'),
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'APPL-001', 'MacBook Air M1 13"', 2, 999.00, 'Delivered', '2024-03-30'),
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'ASUS-003', 'ASUS ZenBook 14 OLED', 1, 999.00, 'Shipped', '2024-04-30'),
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'HP-004', 'HP ProBook 440 G10', 1, 950.00, 'Delivered', '2024-05-18'),
('4285ab84-e6cf-4e9f-9925-b884e33f7dca', 'MSI-001', 'MSI Modern 14 C12M', 1, 699.00, 'Cancelled', '2024-06-26'),
-- User 20
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'APPL-006', 'MacBook Pro M3 14"', 1, 1999.00, 'Delivered', '2024-02-18'),
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'LNVO-002', 'Lenovo IdeaPad Slim 5', 1, 699.00, 'Processing', '2024-04-01'),
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'DELL-007', 'Dell XPS 13 9315', 1, 1499.00, 'Delivered', '2024-05-02'),
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'HP-008', 'HP Omen 16 Gaming', 2, 1299.00, 'Shipped', '2024-05-20'),
('eb55a922-2e4b-45fe-895a-140f9c617eca', 'ASUS-008', 'ASUS ROG Zephyrus G14', 1, 1499.00, 'Delivered', '2024-06-28');
